services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bde_db
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bde_db
    depends_on:
      - db
    networks:
      - bde-network

  db:
    image: postgres:15-alpine
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bde_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bde-network

networks:
  bde-network:
    driver: bridge

volumes:
  postgres_data:
